### ISSUE TITLE
Visualisation : colormap issue of the background

### ISSUE THREAD

**Issue by stoujia** [xgrg/nisnap#11]
Hi !
Thank you for your wonderful work.

I had an issue with the colormap of my background image. It was considered as the same color used for the masks. When we look into the code especially in nisnap/snap.py the function __snap_slices_  , there is the use of a ratio to consider if it's going to be a greyscale or another cmap according to the proportion of intensities under 10.

I resolved this issue by adding 10 to the values of my background image.

Hope this info is going to help 
Best

Steven
![image](https://github.com/user-attachments/assets/60bca6e6-e6bb-47dd-80c1-61cb0457955d)

**Comment by xgrg** [comment]
Thank you Steven for documenting this. 
Your suggestion is the right thing to do. I introduced this ratio so as to guess the type of image and avoid the burden of an extra parameter. Unfortunately it is not robust to all possible cases and may thus require to be adjusted when using some specific data. The alternative being as you write to adjust the image itself, which as a result has an impact on the ratio.
